### ISSUE TITLE
Firefox now supports PnP

### ISSUE THREAD

**Issue by DBDeveloper87** [Freshman-tech/custom-html5-video#32]
Firefox 71 on Windows and 72 on MacOS and Linux now supports PnP; however the code we use to check if the browser supports it doesn't detect it.  Reading the article below, it seems Firefox's implementation is in the shadow DOM, and I can't find a way to add the detections of PnP in Firefox.
https://hacks.mozilla.org/2020/01/how-we-built-picture-in-picture-in-firefox-desktop/?fbclid=IwAR3gETzB--9GwFe8nAfbCytg8wx3wL3PqUhdc0F4o5d4w-w4aXuipaxfld8

**Comment by ayoisaiah** [comment]
From what I understand, Firefox does not use the Picture-in-Picture API that's why the code does not work. With their implementation, you don't need to do anything to add PnP support to your video (works automatically), and it cannot be disabled either (unlike in Chrome). We (developers) have no control over how PnP works in Firefox.

![image](https://user-images.githubusercontent.com/13372163/103148279-4086b500-475e-11eb-9a0b-380591c63661.png)
